version: '2'
services:
  octoprint:
    build: .
    image: octoprint/octoprint
    container_name: octoprint
    ports:
      - 5000:5000
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
     - ./config:/home/octoprint/.octoprint
     - sambashare:/home/pi/.octoprint/watched
    restart: unless-stopped

  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - sambashare:/mnt:z
    command: '-s "OctoShare;/mnt;yes;no;no;bob" -u "bob;bobspasswd"'

volumes:
  sambashare: