version: '2'
services:
  octoprint:
    build: .
    image: octoprint/octoprint
    container_name: octoprint
    ports:
      - 80:5000
      - 22:22
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
     - ./config:/home/octoprint/.octoprint
     - /mnt/watched:/home/pi/.octoprint/watched
    restart: unless-stopped

volumes:
  sambashare: